#ifndef GRAYSENSOR_H_
#define GRAYSENSOR_H_

#include "usart.h"

#define GRAYSENSOR_TX_GPIO_PORT GPIOC
#define GRAYSENSOR_TX_GPIO_PIN  GPIO_PIN_6
#define GRAYSENSOR_RX_GPIO_PORT GPIOC
#define GRAYSENSOR_RX_GPIO_PIN  GPIO_PIN_7

#define GRAYSENSOR_D1_GPIO_PORT   GPIOG      
#define GRAYSENSOR_D1_GPIO_PIN    GPIO_PIN_8
#define GRAYSENSOR_D2_GPIO_PORT   GPIOG      
#define GRAYSENSOR_D2_GPIO_PIN    GPIO_PIN_7
#define GRAYSENSOR_D3_GPIO_PORT   GPIOG      
#define GRAYSENSOR_D3_GPIO_PIN    GPIO_PIN_6
#define GRAYSENSOR_D4_GPIO_PORT   GPIOG      
#define GRAYSENSOR_D4_GPIO_PIN    GPIO_PIN_5
#define GRAYSENSOR_D5_GPIO_PORT   GPIOG      
#define GRAYSENSOR_D5_GPIO_PIN    GPIO_PIN_4
#define GRAYSENSOR_D6_GPIO_PORT   GPIOG      
#define GRAYSENSOR_D6_GPIO_PIN    GPIO_PIN_3
#define GRAYSENSOR_D7_GPIO_PORT   GPIOG      
#define GRAYSENSOR_D7_GPIO_PIN    GPIO_PIN_2
#define GRAYSENSOR_D8_GPIO_PORT   GPIOD      
#define GRAYSENSOR_D8_GPIO_PIN    GPIO_PIN_15
#define GRAYSENSOR_D9_GPIO_PORT   GPIOD      
#define GRAYSENSOR_D9_GPIO_PIN    GPIO_PIN_14
#define GRAYSENSOR_D10_GPIO_PORT  GPIOD      
#define GRAYSENSOR_D10_GPIO_PIN   GPIO_PIN_13
#define GRAYSENSOR_D11_GPIO_PORT  GPIOD      
#define GRAYSENSOR_D11_GPIO_PIN   GPIO_PIN_12
#define GRAYSENSOR_D12_GPIO_PORT  GPIOD      
#define GRAYSENSOR_D12_GPIO_PIN   GPIO_PIN_11
#define GRAYSENSOR_D13_GPIO_PORT  GPIOD      
#define GRAYSENSOR_D13_GPIO_PIN   GPIO_PIN_10
#define GRAYSENSOR_D14_GPIO_PORT  GPIOD      
#define GRAYSENSOR_D14_GPIO_PIN   GPIO_PIN_9
#define GRAYSENSOR_D15_GPIO_PORT  GPIOD      
#define GRAYSENSOR_D15_GPIO_PIN   GPIO_PIN_8

#endif