#ifndef IMAGEPROCESS_H_
#define IMAGEPROCESS_H_

#define IMAGEPROCESS_UART7_TX_GPIO_PORT  GPIOE      
#define IMAGEPROCESS_UART7_TX_GPIO_PIN   GPIO_PIN_8
#define IMAGEPROCESS_UART7_RX_GPIO_PORT  GPIOE 
#define IMAGEPROCESS_UART7_RX_GPIO_PIN   GPIO_PIN_7

#define ImageProcessUartHandle huart7

#endif
