#ifndef INDUCTIVEMOTOR_H_
#define INDUCTIVEMOTOR_H_

#define LEFTINDUCTIVEMOTOR_USART1_TX_GPIO_PORT  GPIOB  
#define LEFTINDUCTIVEMOTOR_USART1_TX_GPIO_PIN   GPIO_PIN_14
#define LEFTINDUCTIVEMOTOR_USART1_RX_GPIO_PORT  GPIOB 
#define LEFTINDUCTIVEMOTOR_USART1_RX_GPIO_PIN   GPIO_PIN_15
#define LEFTINDUCTIVEMOTOR_RST_GPIO_PORT        GPIOD
#define LEFTINDUCTIVEMOTOR_RST_GPIO_PIN         GPIO_PIN_8

#define LeftInductiveMotorUartHandle huart1

#define RIGHTINDUCTIVEMOTOR_UART4_TX_GPIO_PORT  GPIOA     
#define RIGHTINDUCTIVEMOTOR_UART4_TX_GPIO_PIN   GPIO_PIN_0
#define RIGHTINDUCTIVEMOTOR_UART4_RX_GPIO_PORT  GPIOA
#define RIGHTINDUCTIVEMOTOR_UART4_RX_GPIO_PIN   GPIO_PIN_1
#define RIGHTINDUCTIVEMOTOR_RST_GPIO_PORT       GPIOA
#define RIGHTINDUCTIVEMOTOR_RST_GPIO_PIN        GPIO_PIN_2

#define RightInductiveMotorUartHandle huart4
#endif