#ifndef SERVOMOTOR_H_
#define SERVOMOTOR_H_

#include "tim.h"

#define SERVOMOTOR_TIM1_CH1_GPIO_PORT  GPIOE      
#define SERVOMOTOR_TIM1_CH1_GPIO_PIN   GPIO_PIN_9
#define SERVOMOTOR_TIM1_CH2_GPIO_PORT  GPIOE 
#define SERVOMOTOR_TIM1_CH2_GPIO_PIN   GPIO_PIN_11
#define SERVOMOTOR_TIM1_CH3_GPIO_PORT  GPIOE 
#define SERVOMOTOR_TIM1_CH3_GPIO_PIN   GPIO_PIN_13

//CH1和CH3为手臂舵机，CH2为摇头舵机
#define RIGHT_ARM_SERVO_CHANNEL  TIM_CHANNEL_1
#define SHAKE_HEAD_SERVO_CHANNEL  TIM_CHANNEL_2
#define LEFT_ARM_SERVO_CHANNEL TIM_CHANNEL_3

void ServoMotorInit(void);
void ServoMotorAngleSet(uint32_t channel, uint8_t angle);

#endif